using InteractiveReport.Core.Authorization;
using InteractiveReport.Core.Model;
using InteractiveReport.Core.SavedReports;

namespace InteractiveReport.Core.Tests;

public sealed class Oracle11gStoreDdlTests
{
    [Theory]
    [InlineData("INTERACTIVE_REPORT_SAVED", "_TITLE_UX")]
    [InlineData("VERY_LONG_CUSTOM_SAVED_REPORT_PERSISTENCE_TABLE_NAME", "_TITLE_UX")]
    [InlineData("VERY_LONG_CUSTOM_SAVED_REPORT_PERSISTENCE_TABLE_NAME", "_SOURCE_UX")]
    [InlineData("VERY_LONG_CUSTOM_SAVED_REPORT_PERSISTENCE_TABLE_NAME", "_DEFAULT_UX")]
    [InlineData("VERY_LONG_CUSTOM_SAVED_REPORT_PERSISTENCE_TABLE_NAME", "_SEQ")]
    [InlineData("VERY_LONG_CUSTOM_SAVED_REPORT_PERSISTENCE_TABLE_NAME", "_TRG")]
    public void Oracle_identifiers_do_not_exceed_30_characters(string tableName, string suffix)
    {
        var identifier = SqlSavedReportStore.OracleIdentifier(tableName, suffix);
        Assert.True(identifier.Length <= 30, $"Identifier '{identifier}' exceeds 30 characters ({identifier.Length})");
        Assert.EndsWith(suffix, identifier, StringComparison.Ordinal);
    }

    [Fact]
    public void Title_index_name_is_capped_on_oracle()
    {
        var longTable = "A_VERY_LONG_TABLE_NAME_THAT_WOULD_OVERFLOW_30_BYTES";
        var oracleIndex = SqlSavedReportStore.TitleIndexName(longTable, ReportDialect.Oracle11g);
        var sqlServerIndex = SqlSavedReportStore.TitleIndexName(longTable, ReportDialect.SqlServer);

        Assert.True(oracleIndex.Length <= 30);
        Assert.True(sqlServerIndex.Length > 30);
    }

    [Fact]
    public void Saved_reports_table_ddl_for_oracle11g_does_not_use_identity_clause()
    {
        var config = new SavedReportStoreConfig("Oracle11gConn", ReportDialect.Oracle11g, AutoCreate: true, TableName: "IR_SAVED");

        // Let's invoke reflection or verify CreateTableSql behavior via internal
        var ddl = GetPrivateMethodString(typeof(SqlSavedReportStore), "CreateTableSql", config);
        Assert.Contains("ID           NUMBER(19) PRIMARY KEY", ddl);
        Assert.DoesNotContain("GENERATED BY DEFAULT AS IDENTITY", ddl);
    }

    [Fact]
    public void Saved_reports_table_ddl_for_oracle_modern_uses_identity_clause()
    {
        var config = new SavedReportStoreConfig("OracleModernConn", ReportDialect.Oracle, AutoCreate: true, TableName: "IR_SAVED");
        var ddl = GetPrivateMethodString(typeof(SqlSavedReportStore), "CreateTableSql", config);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", ddl);
    }

    [Fact]
    public void Authorization_store_table_ddl_supports_oracle11g()
    {
        var config = new ReportAuthorizationStoreConfig("Oracle11gConn", ReportDialect.Oracle11g, AutoCreate: true, TableName: "IR_AUTH");
        var ddl = GetPrivateMethodString(typeof(SqlReportAuthorizationStore), "CreateTableSql", config);
        Assert.Contains("CREATE TABLE \"IR_AUTH\"", ddl);
        Assert.Contains("ID             VARCHAR2(80) PRIMARY KEY", ddl);
    }

    private static string GetPrivateMethodString(Type type, string methodName, object argument)
    {
        var method = type.GetMethod(methodName, System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
        Assert.NotNull(method);
        return (string)method.Invoke(null, [argument])!;
    }
}
