using InteractiveReport.Core.Execution;
using Microsoft.Extensions.Logging;
using Xunit.Sdk;

namespace InteractiveReport.Core.Tests;

/// <summary>
/// The guard must reject what an Oracle 11g server rejects and accept what it accepts; the
/// 11g-mode corpus is only meaningful if this holds. Not environment-gated: no database is
/// touched. Messages go through the same logging extension the engine uses.
/// </summary>
public sealed class Oracle11gVocabularyGuardTests
{
    private static readonly Oracle11gVocabularyGuard<ReportExecutor> Guard = new();

    [Theory]
    [InlineData("SELECT \"ID\" FROM \"ORDERS\" ORDER BY \"ID\" OFFSET :p0 ROWS FETCH NEXT :p1 ROWS ONLY", "OFFSET")]
    [InlineData("SELECT \"ID\" FROM \"ORDERS\" FETCH FIRST 10 ROWS ONLY", "FETCH FIRST/NEXT")]
    [InlineData("CREATE TABLE \"T\" (ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)", "identity column")]
    [InlineData("SELECT * FROM \"A\" CROSS APPLY (SELECT 1 FROM DUAL) \"B\"", "APPLY")]
    [InlineData("SELECT JSON_VALUE(\"DOC\", '$.id') FROM \"T\"", "JSON functions")]
    [InlineData("SELECT LISTAGG(\"X\", ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY \"X\") FROM \"T\"", "ON OVERFLOW")]
    [InlineData("SELECT TO_DATE(\"X\" DEFAULT NULL ON CONVERSION ERROR) FROM \"T\"", "ON CONVERSION ERROR")]
    [InlineData("SELECT \"X\" FROM \"T\" ORDER BY \"X\" COLLATE BINARY_CI", "COLLATE")]
    public void Post_11g_syntax_fails_the_test_that_emitted_it(string sql, string construct)
    {
        var failure = Assert.Throws<XunitException>(() => Guard.LogDebug("Executing report SQL:\n{Sql}", sql));

        Assert.Contains(construct, failure.Message);
        Assert.Contains(sql, failure.Message);
    }

    [Fact]
    public void Identifiers_and_bind_names_over_30_bytes_fail()
    {
        var longIdentifier = new string('X', 31);
        var quoted = Assert.Throws<XunitException>(() => Guard.LogDebug(
            "Executing report SQL:\n{Sql}", $"SELECT \"{longIdentifier}\" FROM \"T\""));
        Assert.Contains(longIdentifier, quoted.Message);

        // 30 bytes, not 30 characters: an accented name reaches the limit sooner.
        var accented = new string('é', 16);
        Assert.Throws<XunitException>(() => Guard.LogDebug(
            "Executing report SQL:\n{Sql}", $"SELECT \"{accented}\" FROM \"T\""));

        var bind = Assert.Throws<XunitException>(() => Guard.LogDebug(
            "Executing report SQL:\n{Sql}", $"SELECT 1 FROM DUAL WHERE 1 = :p{new string('9', 30)}"));
        Assert.Contains("exceeds 30 bytes", bind.Message);
    }

    [Fact]
    public void Eleven_g_vocabulary_and_other_log_events_pass()
    {
        Guard.LogDebug(
            "Executing report SQL:\n{Sql}",
            "SELECT \"ID\", \"CUSTOMER\" FROM (SELECT \"results_wrapper\".*, ROWNUM \"row_num\" FROM ("
            + "SELECT \"__irc0\" AS \"ID\", \"__irc1\" AS \"CUSTOMER\", ROW_NUMBER() OVER (ORDER BY \"__irc0\") \"rn\" "
            + "FROM \"ir_rel_0\" WHERE TRUNC(\"__irc2\", 'MM') = TO_DATE(:p0, 'YYYY-MM-DD') "
            + "AND EXTRACT(YEAR FROM \"__irc2\") = :p1 AND \"__irc1\" LIKE :p2 ESCAPE '\\' ORDER BY \"__irc0\""
            + ") \"results_wrapper\" WHERE ROWNUM <= :p3) WHERE \"row_num\" > :p4");
        Guard.LogDebug(
            "Executing report SQL:\n{Sql}",
            "BEGIN\n  OPEN :irResult0 FOR\n    SELECT COUNT(*) FROM \"ir_rel_0\";\nEND;");
        Guard.LogDebug(
            "Executing report SQL:\n{Sql}",
            $"INSERT INTO \"{new string('T', 30)}\" (\"A\") VALUES (:p0) RETURNING ID INTO :ir_generated_id");
        Guard.LogError(new InvalidOperationException("OFFSET 1 ROWS"), "Report failed: {Summary}", "FETCH FIRST is fine in prose");
    }
}
