<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\InteractiveReport.Core\InteractiveReport.Core.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.AspNetCore\InteractiveReport.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.Json\InteractiveReport.Client.Json.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.FileDownload\InteractiveReport.Client.FileDownload.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.GraphQL\InteractiveReport.Client.GraphQL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="8.3.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="ReportDocuments\**\*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
