<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InteractiveReport.AspNetCore\InteractiveReport.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.Json\InteractiveReport.Client.Json.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.FileDownload\InteractiveReport.Client.FileDownload.csproj" />
    <ProjectReference Include="..\..\src\InteractiveReport.Client.GraphQL\InteractiveReport.Client.GraphQL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="InteractiveReport.Client.Json" />
    <Using Include="InteractiveReport.Client.FileDownload" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\PersistenceHttpScenario.cs" Link="PersistenceHttpScenario.cs" />
  </ItemGroup>

</Project>
